{'name': 'Tada Integration',
'summary': 'Integrates customer, product, and order.',
'version': '1.0',
'author': 'Arkana Teknologi',
'website': 'https://arkanateknologi.co.id',
'category': 'Sales',
'depends': ['sale_stock', 'web_widget_image_url', 'delivery'],
'data': ['security/ir.model.access.csv',
         'data/cron_data.xml',
         'data/tada_data.xml',
         'data/delivery_carrier.xml',
         'wizard/tada_authenticate_wizard.xml',
         'views/account_views.xml',
         'views/tada_views.xml',
         'views/tada_store_views.xml',
         'views/tada_product_views.xml',
         'views/tada_order_views.xml',
         'views/stock_picking_views.xml',
         'views/sale_order_views.xml',
         'views/menu.xml'
         ]
}